GET http://localhost:8080/musicas

###

POST http://localhost:8080/musicas
Content-Type: application/json

{  
        
        "nome_musica": "333",
        "album_musica": "444 morram todos",
        "artista_musica": "Crentue",
        "tempo_duracao": "28:80"
}

###

PUT http://localhost:8080/musicas/3
Content-Type: application/json

{
     "nome_musica": "Carque com muciloun",
        "album_musica": "444 morram todos",
        "artista_musica": "bradCaoirentue",
        "tempo_duracao": "10:00"
}

###

DELETE http://localhost:8080/musica/4